export const projects = [
    {
        id: 'bind',
        name: 'Bind',
        thumbnail: '/projects/bind.png',
        year: '24',
        projectLink: 'https://bind-app-demo.vercel.app',
        githubLink: 'https://github.com/BimaPn/bind-server',
    },
    {
        id: 'jitu',
        name: 'Jitu!',
        thumbnail: '/projects/jitu.png',
        year: '24',
        projectLink: '#',
        githubLink: 'https://github.com/fabianazh/jitu',
    },
    {
        id: 'tictactest',
        name: 'TicTacTest',
        year: '24',
        thumbnail: '/projects/tictactest.png',
        projectLink: 'https://fabianazh.github.io/tic-tac-test',
        githubLink: 'https://github.com/fabianazh/tic-tac-test',
    },
    {
        id: 'zufar-portfolio',
        name: 'Portfolio Web',
        thumbnail: '/projects/portfolio.png',
        year: '24',
        projectLink: 'https://zufarms.vercel.app',
        githubLink: 'https://fabianazh.github.io/portfolio-zufar',
    },
    {
        id: 'quranku',
        name: 'QuranKu',
        thumbnail: '/projects/quranku.png',
        year: '23',
        projectLink: 'https://quranku-one.vercel.app',
        githubLink: 'https://github.com/fabianazh/quranku',
    },
    {
        id: 'starbucks-clone',
        name: 'Starbucks Clone',
        thumbnail: '/projects/starbucks.png',
        year: '23',
        projectLink: 'https://fabianazh.github.io/starbucks-clone',
        githubLink: 'https://github.com/fabianazh/quranku',
    },
]
